---
title: "class activity 3"
author: "Minruo Wang"
date: "10/2/2019"
output: html_document
---

### Learn  
#### Useful links  
[ggplot2 website](https://ggplot2.tidyverse.org/reference/)  
[R Graphic Cookbook](http://www.cookbook-r.com/Graphs/)

#### Mapping aesthetic to data to = layer  
```{r}
# install.packages("ggplot2")
library(ggplot2)

ggplot(diamonds, aes(x = price, y = carat)) +
  geom_point()
```

#### Two layers
```{r}
ggplot(mpg, aes(reorder(class, hwy), hwy)) +
  geom_jitter() + # adds a small amount of random variation to the location of each point
  geom_boxplot()
```

```{r}
#Plot count
ggplot(diamonds, aes(depth)) +
  geom_histogram(aes(y = ..count..), binwidth=0.2) +
  facet_wrap(~ cut) + xlim(50, 70)

#Plot density
ggplot(diamonds, aes(depth)) +
  geom_histogram(aes(y = ..density..), binwidth=0.2) +
  facet_wrap(~ cut) + xlim(50, 70)
```

```{r}
ggplot(mpg, aes(displ, hwy, color = class)) +
  geom_point()
```
  
### Exercise
##### 1. Can you create a line graph using the "economics_long" data set that shows change over time in "value01" for different categories of "variable"?  
  
```{r}
# show in one graph
ggplot(economics_long, aes(date, value01, color = variable)) +
  geom_line()
```
  
```{r}
# show in facet
ggplot(economics_long, aes(x = date, y = value01, color = variable)) +
  geom_line() +
  facet_wrap(~ variable)
```

##### 2. If you would like to recreate the Minard graphic of Napoleon's Troops the code is below and the data is in this repo.
```{r}
# load and merge the data
cities <- read.table("cities.txt", header = TRUE, sep = "")
troops <- read.table("troops.txt", header = TRUE, sep = "")
temps <- read.table("temps.txt", header = TRUE, sep = "")
Napo <- merge(cities, troops, by = c("long", "lat"), all = TRUE)
Napoleon <- merge(Napo, temps, by = "long", all = TRUE)
```


```{r}
# Napoleon's troops route
route <- ggplot(Napoleon, aes(long, lat)) +
  geom_path(aes(size = survivors, colour = direction,
                group = interaction(group, direction)), 
                data = troops) +
  geom_text(aes(label = city), hjust = 0, vjust = 1, size = 4) +  
  scale_x_continuous("", limits = c(24, 39)) +
  scale_y_continuous("") +
  scale_colour_manual(values = c("grey50","red")) +
  scale_size(range = c(1, 10))
# show the graph
route
# save the graph using ggsave
ggsave(route, file = "Napoleon-route.png")
```

